export const CREATE: string = 'CREATE'
export const UPDATE: string = 'UPDATE'
export const CHECK: string = 'CHECK'
export const UPDATE_EMAIL: string = 'UPDATE_EMAIL'
export const UPDATE_PASSWORD: string = 'UPDATE_PASSWORD'
